### ISSUE TITLE
Bitrate menu should be reenabled without help of separate extension

### ISSUE THREAD

**Issue by ItsNickBarry** [ItsNickBarry/netflix-max-bitrate#2]
It would be useful to remove the dependency on the netflix-1080p-firefox extension, especially now that that extension has been removed from the [Firefox addons site](https://github.com/vladikoff/netflix-1080p-firefox/issues/28).

**Comment by viktorjk** [comment]
There's a [Firefox](https://addons.mozilla.org/de/firefox/addon/better-netflix/)/[Chrome](https://chrome.google.com/webstore/detail/better-netflix/lgaajejckkabgbineealeijjlffiigah) add-on called "Better Netflix" ([code repo at gitlab.com](https://gitlab.com/konstantin-mueller/better-netflix)) which has several functions, among them the enablement of a video bitrate selection menu and a configuration option to automatically select the highest available bitrate. It works for me in Firefox (I don't use Chrome/Chromium).

Unfortunately I'm not a (JS) programmer, so I can't help you with the code. It looks like a modified Cadmium Playercore is used, so maybe you can make your add-on work on its own with the same trick, but that has of course the problem that your add-on could be banned from the Firefox add-on site. You could also create another branch in your repo with the necessary changes, but not upload this branch to the add-on site, so that people can at least build this extension on their own.

**Comment by ItsNickBarry** [comment]
Thanks for the information.  You appear to be correct, that Better Netflix uses modified Netflix code.  I don't think it's worth it to try to host it here, since any user who is willing to build and install an addon manually is probably able to install a dependency.

Thought this addon is probably redundant anyway.  I didn't realize that Better Netflix had this feature.  I've linked to Better Netflix in the description on the addon site.
